apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: cicd-tools
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cicd-tools
    app.kubernetes.io/part-of: bonfire-cicd-tools
  name: cicd-tools
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: cicd-tools
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: cicd-tools
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/bonfire-cicd-tools/cicd-tools@sha256:fb479f805b7242c8cb1c83e6ce0572958d9247a351d6305d634292d641ee93fa
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
