apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: cicd-tools
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-migration-tenant/bonfire-cicd-tools/cicd-tools@sha256:fe88b3e38f427a77fdeb2858ab9d08703a99777482e0e3d2b8708d192584042c
        name: container-image
        resources: {}
status: {}
